/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BackTop: typeof import('./components/BackTop/BackTop.vue')['default']
    CopyButton: typeof import('./components/CopyButton/index.vue')['default']
    ECharts: typeof import('./components/ECharts/index.vue')['default']
    Editor: typeof import('./components/MonacoEditor/Editor.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElText: typeof import('element-plus/es')['ElText']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElTreeSelect: typeof import('element-plus/es')['ElTreeSelect']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    GithubCorner: typeof import('./components/GithubCorner/index.vue')['default']
    GlobalTIP: typeof import('./components/GlobalTip/GlobalTIP.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    InputTag: typeof import('./components/InputTag/index.vue')['default']
    MonacoEditor: typeof import('./components/MonacoEditor/index.vue')['default']
    PageContent: typeof import('./components/Form/PageContent.vue')['default']
    PageForm: typeof import('./components/Form/PageForm.vue')['default']
    PageModal: typeof import('./components/Form/PageModal.vue')['default']
    PageSearch: typeof import('./components/Form/PageSearch.vue')['default']
    Pagination: typeof import('./components/Pagination/index.vue')['default']
    TableSelect: typeof import('./components/TableSelect/index.vue')['default']
    TextScroll: typeof import('./components/TextScroll/index.vue')['default']
    UploadCos: typeof import('./components/Upload/uploadCos.vue')['default']
    UploadLocal: typeof import('./components/Upload/uploadLocal.vue')['default']
    WangEditor: typeof import('./components/WangEditor/index.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
